[versions]
graalvm = "24.1.0"

[libraries]
# Allay
allay = { group = "org.allaymc.allay", name = "server", version = "master-SNAPSHOT" }
# GraalVM
polyglot = { group = "org.graalvm.polyglot", name = "polyglot", version.ref = "graalvm" }
javascript = { group = "org.graalvm.polyglot", name = "js-community", version.ref = "graalvm" }
python = { group = "org.graalvm.polyglot", name = "python-community", version.ref = "graalvm" }
chromeinspector = { group = "org.graalvm.tools", name = "chromeinspector-tool", version.ref = "graalvm" }
# Lombok
lombok = { group = "org.projectlombok", name = "lombok", version = "1.18.34" }